### ISSUE TITLE
Requesting tags: mux: variable nvidia-gpu-device-plugin@sha256 doesn't match, expected regex

### ISSUE THREAD

**Issue by yanc0** [weaveworks/flux#1103]
Hi,

Flux output error logs in GKE 1.10, complaining about a non matching regex. The nvidia-gpu-device-plugin image is used in a DaemonSet (same name) located in kube-system namespace.

```
ts=2018-05-29T06:44:44.011090829Z caller=warming.go:162 component=warmer canonical_name=k8s.gcr.io/nvidia-gpu-device-plugin@sha256
auth={map[]} err="requesting tags: mux: variable \"nvidia-gpu-device-plugin@sha256\" doesn't match, expected \"^(?:(?:[a-zA-Z0-9]|
[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9])(?:(?:\\\\.(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]))+)?(?::[0-9]+)?/)?[a-z0-9]+(?:(?:
(?:[._]|__|[-]*)[a-z0-9]+)+)?(?:(?:/[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?)+)?$\""
```

It seems that GKE use a SHA256 id instead of a tag. I don't know how Flux can manage this kind of specificity but it is a bit noisy when we look at the logs.

```
image: k8s.gcr.io/nvidia-gpu-device-plugin@sha256:0842734032018be107fa2490c98156992911e3e1f2a21e059ff0105b07dd8e9e
```

**Comment by squaremo** [comment]
Ugh, yeah Flux doesn't handle images that use digests instead of tags. It definitely should -- for many purposes, using digests is preferable to using tags.

Parsing image refs that use digests isn't difficult, and we already fetch digests from the image registries. The hurdle is figuring out when it should use digests instead tags (perhaps when the repository uses a digest?), and how to represent them in the user interface, and that sort of thing.

See #885.

**Comment by yanc0** [comment]
Thanks for the explanation and sorry for the duplicate ;)

**Comment by squaremo** [comment]
(basically all the labels that indicate it would be good to address this ..)
