### ISSUE TITLE
helm-operator:  does not match namespace

### ISSUE THREAD

**Issue by endrec** [weaveworks/flux#1293]
In some charts (e.g. coreos/kube-prometheus) a few resource is created in the "kube-system" namespace, and not in the release namespace.
helm-operatot logs this error:

```
ts=2018-08-17T12:56:44.566927601Z caller=release.go:296 component=release output="secret \"alertmanager-monitoring\" annotated\n[...]servicemonitor \"monitoring-prometheus\" annotated\nthe namespace from the provided object \"kube-system\" does not match the namespace \"monitoring\". You must pass '--namespace=kube-system' to perform this operation.\nthe namespace from the provided object \"kube-system\" does not match the namespace \"monitoring\". You must pass '--namespace=kube-system' to perform this operation.\nthe namespace from the provided object \"kube-system\" does not match the namespace \"monitoring\". You must pass '--namespace=kube-system' to perform this operation.\n" err="exit status 1"
```

Despite of this error, the release seems working fine.

**Comment by ahmadiq** [comment]
+1 We're facing this issue as well.

**Comment by samisq** [comment]
+1 We're facing this exact issue too. Can this be safely ignored (for now)?

**Comment by nmaupu** [comment]
Same issue here. We are using prometheus-operator and our charts create a `servicemonitor` object in the same namespace as the prometheus-operator itself along with the resources needed by the chart's release.
I confirm, everything is created as expected but the error is not very clear as this is the expected behavior and should be safely ignored or not...
