### ISSUE TITLE
Explicit means of switching automation and image DB off

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#1316]
> I would like to  disable the registry scanning feature for now. I can see in the introduction this feature can be disabled but i can not find how to do that.

**Comment by dpgeekzero** [comment]
Not sure I understand.  The intro still says that this can be disabled.  Can it be?
I have no use for this feature, but my logs are full of registry scan messages.

**Comment by squaremo** [comment]
@dpgeekzero I think I will have posted this as a reminder to either add the ability to disable registry scanning entirely, or to find and excise the claim to have that ability.

We can also damp down the amount of logging done by the registry scanning, e.g., by suppressing repeated messages.

**Comment by markbenschop** [comment]
In my case we run a single registry for test, acceptance and prod. Registry scanning would only make sense for test. We don't want to retag images for the different environments.
Anyway to have the option to disable will serve some use cases imo.

**Comment by squaremo** [comment]
@markbenschop Do you mean you would want scanning to be done in one place, but the results used for multiple environments? Or, that you don't need the image database for acceptance or prod -- you always make changes to their configs by some means other than flux?

**Comment by markbenschop** [comment]
i mean I have T/A/P k8s clusters. On T i want to scan the registry and automatically install new container versions and run integration tests. On A I only want to install the new version after the integration test (triggered by e.g. Jenkins) succeed. After successful integration test on T scripts ran by Jenkins another script will modify the flux git repository of A. So in this scenario we do not want A to install new pods because it found them in the registry but have more control. Disabling the registry scanning would make sense here.

**Comment by squaremo** [comment]
@markbenschop OK got it. Automation is opt-in (you have to annotate the workloads for them to get automated updates), so you can just leave your acceptance testing and production config unannotated, and fluxd will sync it, but not modify it.

fluxd will still do some work you don't strictly speaking need -- it'll scan the registries for the image versions -- but it won't use that information unless you query for it.

**Comment by markbenschop** [comment]
Thanks @squaremo I understand now. That solves it.

**Comment by squaremo** [comment]
#1654 effectively fixes the image DB part of this, since you can now exclude all image registry domains from scanning.
