### ISSUE TITLE
Question: Can flux with helm support refer to a helm chart that is not in the same git repo

### ISSUE THREAD

**Issue by tlvu** [weaveworks/flux#1379]
In the [flux-helm-test](https://github.com/weaveworks/flux-helm-test) repo, the charts are inside the same flux git repo.

In [helm-integration.md](https://github.com/weaveworks/flux/blob/master/site/helm-integration.md) we see "chartGitPath ... path (from repo root) to a Chart subdirectory".  To me, it seems to imply the charts files have to be physically in the same repo as the flux git repo.

What if we want to use published charts.  How can we refer to a published chart?

**Comment by squaremo** [comment]
> To me, it seems to imply the charts files have to be physically in the same repo as the flux git repo.

You supply the helm operator with a git URL (and branch), and the charts are given by paths within that repo. It does not have to be the same git repo as the one you give to fluxd. If you use a different repo, you'll have to supply a different deploy key secret and so on.

> if we want to use published charts. How can we refer to a published chart?

At present, the helm operator supports only releasing charts from git. We'd like to add support for releasing charts from a Helm repo: https://github.com/weaveworks/flux/issues/1131 since that will make it much more useful.

**Comment by tlvu** [comment]
Replying to my own question after testing, chartGitPath can not point to a remote git url.

**Comment by squaremo** [comment]
@tlvu I think #1131 and the PR #1382 constitute an answer to your question -- do you agree? If so, we can close this issue.

**Comment by tlvu** [comment]
Agree that if issue #1131 is done then that satisfy our requirements.  Thanks for the follow up.
