### ISSUE TITLE
Accidentally quadratic

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#139]
- [x] https://github.com/weaveworks/fluxy/blob/master/helper.go#L86 `helper.AllReleasableImages`

Asks for each service in turn, and fetches the containers for each with `platform.ContainersFor(...)`, which itself fetches all the replication controllers and deployments and examines each one to see if it matches the service.
- [x] https://github.com/weaveworks/fluxy/blob/master/release/release.go#L154 `release.releaseAllToLatest`

Fetches the image metadata for each image mentioned by a container used by a service, and these images could (in principle) all be the same, and are certainly repeated in practice.
- [x] https://github.com/weaveworks/fluxy/blob/master/server.go#L68 `server.ListImages` and `server.ListServices`

These both ask for all the services, then iterate through all the rcs/deployments similar to the first item above.

**Comment by philwinder** [comment]
Regarding [previous comment](https://github.com/weaveworks/flux/issues/139#issuecomment-249526428)

I investigated `kubeservice` and the python code is operating on the files that have been downloaded from the GH repo. I.e the files are local. Yes we iterate over all files to find a service, but there's no network latency involved with that.

So I don't see any value in attempting to reverse the way we do it because it would require a fairly large rewrite (and a lot of prior knowledge) and it seems to work well enough for the moment.

Closing because of this conclusion.
