### ISSUE TITLE
Flux kubectl  version 1.9  causing validation issues with valid 1.11 CRDs

### ISSUE THREAD

**Issue by hartman17** [weaveworks/flux#1392]
Attempting to deploy a CRD that is a valid kubectl 1.11 object is failing the validation check because flux is running kubectl version 1.9.    

**FLUX Log error:**    

2018-09-25T13:02:35.693380942Z caller=sync.go:164 component=cluster method=Sync cmd="kubectl apply -f -" took=171.998444ms err="running kubectl: error: error validating \"STDIN\": error validating data: ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.profiles.items): invalid type for io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray: got \"map\", expected \"\"; if

**Comment by squaremo** [comment]
It's a tricky one, because [kubectl supports only one version back](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew) -- so if we bake in v1.11, we lose support for Kubernetes v1.9. We can bake in v1.10, to support v1.11 and v1.9, and lose v1.8 -- that's not so bad, since people ought to have upgraded to 1.9 by now.

There is a mechanism for using your own `kubectl` -- you can pass the `--kubernetes-kubectl` flag to fluxd, pointing at a kubectl you've mounted. This isn't especially convenient, I admit.

**Comment by mellena1** [comment]
I'm not sure if I entirely understand the scope of this problem, but maybe making separate tagged images with different `kubectl` versions would be beneficial. Like `flux:1.5.0-kube1.9`, `flux:1.5.0-kube1.10`, etc. Obviously you can't support every version, but having the option between the past few versions might be good enough. Just a thought.

**Comment by stefanprodan** [comment]
This has been solved in [Flux 1.8.1](https://github.com/weaveworks/flux/releases/tag/1.8.1) that comes with kubectl 1.11.3
