### ISSUE TITLE
Completely integrate fluxy to service-conf workflows

### ISSUE THREAD

**Issue by peterbourgon** [weaveworks/flux#143]
Including removing wcloud hooks, instructions, deployments, etc.

**Comment by squaremo** [comment]
Flux is running in dev and prod, and accessible by using the dev URL and token, or the prod token (the URL has the correct default) respectively.

Left to do:

 - [ ] Automate all services in dev, by finding out which images they involve, blacklisting those in deploy, then switching automation on in flux dev. (A bit of care must be taken, because services share images, and it's images that are blacklisted rather than services)
 - [ ] Update the weave deployment docs

**Comment by rade** [comment]
@paulbellamy please elaborate on your plans for "Figure out how deploy's auto-config-applying can be made to live with Flux".

**Comment by paulbellamy** [comment]
Re: auto-fixing kubediffs

In wcloud, the syncing and kubediffing is done as an internal scheduled job (so that we can keep track of detected diffs and draw a nice UI of them). This is a bit of a weave cloud specific thing to do, so we decided it shouldn't be an internal thing to flux.

I've built [this docker image](https://github.com/weaveworks/monitoring/tree/master/kubefix), which could be used to either call wcloud, or flux when there is a kubediff detected. We can use that to change it over, and implement the auto-fix behaviour for flux.

**Comment by paulbellamy** [comment]
Notes:
- I'm skipping several things, because they are only a deployment (not a service), so it doesn't show up in flux's service list. (TODO: file/reference an issue about this):
  - `monitoring/metrics`
  - `default/proxy`

**Comment by paulbellamy** [comment]
- [ ] remove wcloud from circle.ymls, etc...

**Comment by paulbellamy** [comment]
Remaining steps are cleanup, so closing this.
