### ISSUE TITLE
git clone in flux-helm-operator pod cannot read from remote repository

### ISSUE THREAD

**Issue by justdavid** [weaveworks/flux#1457]
Hi,
I encounter the following whereby git clone could not read from remote repository. I was reading the other post and changed hostname to IP address. Still the same issue.

W1022 10:18:29.148995       5 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
ts=2018-10-22T10:18:29.161062237Z caller=helm.go:81 component=helm info="Helm client set up"
ts=2018-10-22T10:18:29.161203362Z caller=main.go:196 component=helm-operator info="Attempting to clone repo ..." url=ssh://git@192.168.200.86/srv/git/gitops-helm.git
ts=2018-10-22T10:18:29.237831797Z caller=main.go:201 component=helm-operator error="git clone --mirror: fatal: Could not read from remote repository."

I tried to exec into that pod so that i can check if i could git clone inside the pod but it says "unable to upgrade connection: container not found flux-helm-operator" and it keeps on restarting by its own.

Outside the pod, I am able to "git clone --mirror ssh://git@192.168.200.86/srv/git/gitops-helm.git" successfully.  

Appreciate any help.

Thanks in advance 
David

**Comment by squaremo** [comment]
>  I was reading the other post and changed hostname to IP address.

Which other post?

The most likely cause is that SSH is refusing to connect to a host it doesn't have a key for. It is a bit of a pain with the helm-operator image, because (as you've noticed) it tends to exit if it can't clone the repo. If you're using the same git repo as in fluxd, you can exec into the fluxd container to try it out.

https://github.com/weaveworks/flux/blob/master/site/standalone-setup.md#using-a-private-git-host has some instructions and explanation.

**Comment by justdavid** [comment]
I was referencing this post: Git clone fails in the helm-operator for private git repos #1167

Many thanks, I will try this out and update the results.

**Comment by squaremo** [comment]
Good troubleshooting! Thanks for persevering, and documenting it here.

It is not easy to understand why things are going wrong, when they are going wrong. I wonder what flux can do better here.
