### ISSUE TITLE
Insecure registries behave differently than Docker Daemon

### ISSUE THREAD

**Issue by Timer** [weaveworks/flux#1497]
Currently, passing flux an insecure registry only toggles the HTTP request to use `http` over `https`.

It also needs to pass `InsecureSkipVerify` to the http client to ignore invalid SSL certificates (e.g. self signed).

ref: `registry/client_factory.go`

**Comment by squaremo** [comment]
> It also needs to pass `InsecureSkipVerify` to the http client to ignore invalid SSL certificates (e.g. self signed).

Why is it getting certificates if it's using HTTP?

**Comment by Timer** [comment]
The load balancer in front of the registry is redirecting.
In this scenario, we're purposely using a bad cert.

**Comment by squaremo** [comment]
> The load balancer in front of the registry is redirecting.
> In this scenario, we're purposely using a bad cert.

OK, so the index has an address with HTTP, but the manifests are hosted somewhere using HTTPS and using a self-signed cert? In that case, yes I guess there would need to be either an extension of the meaning of `--registry-insecure-host`, or another flag, to switch off SSL host checking.

**Comment by Timer** [comment]
Given docker's behavior for an "insecure registry" is to ignore invalid certs **and** plain old http, adding this behavior to the existing flag is OK.

**Comment by squaremo** [comment]
The way Docker treats the `--insecure-registry` flag is a bit different https://docs.docker.com/registry/insecure/:

 1. It tries https, and and if available, ignores certificate verification
 2. If https is not available, it just uses http

So the effect is that it'll ignore host verification when using https. It's not clear from the docs that it will do this for all hostnames involved in fetching, e.g., if the manifests or layers are elsewhere, since it's described in the context of using the reference implementation.

Docker won't send credentials to an insecure registry, whether it's available on https or not. Perhaps we should have the same constraint? I would feel much better about transparently extending the insecurity to redirections, if that were the case. WDYT?

**Comment by Timer** [comment]
Hmm, I'm seeing it send credentials to an insecure registry on my end. I'm open for whatever, but I think we need more testing on the credentials front.

**Comment by squaremo** [comment]
> I'm seeing it send credentials to an insecure registry on my end

Is "it" Docker, or flux?

**Comment by Timer** [comment]
Docker, though through TFS.
