### ISSUE TITLE
valueFiles was removed but is needed

### ISSUE THREAD

**Issue by Morriz** [weaveworks/flux#1505]
To remove `valueFiles` (now exchanged for `valueFileSecrets`) is a bad move imo, as this obfuscates values that don't need masking, and removes the possibility to do a manual `helm install` with a `values.yaml` file, as we can't use that anymore. Please put it back.

**Comment by squaremo** [comment]
`valueFiles` was only present in a PR branch, and only briefly. Is that what you're referring to? If so, I'm not sure it worked the way you think it did -- specifically, with respect to

> removes the possibility to do a manual helm install with a values.yaml file, as we can't use that anymore

 -- I don't think it _enabled_ this possibility, any more or less so that `valueFileSecrets`. But you may be referring to another feature, or there is some interpretation I am missing. Perhaps you could elaborate on how you were expecting to use it, in that case.

**Comment by Smirl** [comment]
There was a conversation on this commit https://github.com/weaveworks/flux/commit/f2c094bb80e566c7ec22406f02b22142602901a4#commitcomment-31251200

**Comment by Morriz** [comment]
I understand. I am already happy I could use the intermediate SealedSecrets to load them :)

**Comment by squaremo** [comment]
OK cool, thanks @Morriz. For the scenario of having a values.yaml file in git that you can use with `helm install`, you could keep both the values.yaml and the secret created from it, in git; and verify in CI that the latter is correct.
