### ISSUE TITLE
Image tag in HelmRelease is erroneously converted to another value

### ISSUE THREAD

**Issue by gtseres** [weaveworks/flux#1743]
We have a `HelmRelease` object in Git, with the following section under the `values` key:
```
image:
      repository: REDACTED
      tag: 0362525
```

When Flux grabbed the release to deploy it, we got an `ImagePullBackoff`. After some investigation, we noticed that the `tag` field in the Flux configuration (`kubectl get helmreleases`) was a different one from the one above. It seems that when the tag is a number (not enclosed in quotes), its value is somehow changed by Flux when the `HelmRelease` is fetched and parsed from git. Unfortunately I do not have the value that we saw in the parsed object. Enclosing the tag in quotes solves the issue.

**Comment by stefanprodan** [comment]
@gtseres this is how YAML works, if a value resembles a number it will convert it. When using numbers as image tags you have to enclosed them in quotes.

**Comment by hiddeco** [comment]
When working with numbers that should be interpreted as strings you should always enclose them in quotes as otherwise they will indeed end up as something else.

Flux already does this when updating manifests (`tag: '0362525'`) so my assumption is the `HelmRelease` got added by a human without quotes around the tag. If you would have given a manual `helm install` the `HelmRelease` values the same mutation would have occurred.
