### ISSUE TITLE
Changing repository url of `HelmRelease` doesn't sync

### ISSUE THREAD

**Issue by hpurmann** [weaveworks/flux#1850]
We were changing the URL of the git repository of a `HelmRelease`.
Unfortunately, the Helm Operator didn't pick that up and didn't trigger a sync.

Deleting the pod of `helm-operator`, thus restarting it, helped. We would expect that it automatically picks up the new url without a restart.

We also tried deleting the `HelmRelease` resource. Flux was re-creating the `HelmRelease` resource but still the old repository URL was used by `helm-operator`. Is this a known issue?

**Comment by hiddeco** [comment]
> Is this a known issue?

You just made it a known issue.

The problem is that chart clones being stored against the `releaseName`. In case a previous chart clone [is found](https://github.com/weaveworks/flux/blob/master/integrations/helm/chartsync/chartsync.go#L307) the operator will [never look](https://github.com/weaveworks/flux/blob/master/integrations/helm/chartsync/chartsync.go#L313) at the git source in the `HelmRelease` again as it already has a clone for the said release name.

**Comment by hpurmann** [comment]
Thanks a lot for the quick response and for working on a fix already! We appreciate.
