### ISSUE TITLE
Regexp matching not working as expected

### ISSUE THREAD

**Issue by southbanksoftwaredeveloper** [weaveworks/flux#1914]
I have two environments, `dev` and `stg`. I am tagging the images with both short `SHA-256` and semantic versions. I only want to maintain the `SHA-2` hashes in my code.

I have the following annotation:

```
flux.weave.works/tag.my-stg-service: regexp:^aa7ad0f$
```
However, the tag always gets reset to `0.0.13`. They are essentially the same images, but I would like to maintain a history of the SHA2 hashes.
I also tried 
```
flux.weave.works/tag.my-stg-service: regexp:aa7ad0f
```

For the dev environment, I tried the following
```
flux.weave.works/tag.api-gateway: regexp:^([0-9a-f]{7})$
```
However, this also gets reset to 
```
tag: 0.0.13
```
Am I not writing the regexes correctly?

**Comment by squaremo** [comment]
What does the rest of the manifest look like?

**Comment by squaremo** [comment]
The regexp looks like it'll do what you want. My guess is that it's not being applied to the container you want it to be, which just ends up getting whatever is the most recent image. Since you mention

    tag: 0.0.13

I think you're supplying the image in the `.spec.values` sections of a HelmRelease. These get interpreted by fluxd in a fixed way, and that might not match your expectation. The formats are explained here: https://github.com/weaveworks/flux/blob/master/site/helm-integration.md#upgrading-images-in-a-helmrelease-using-flux -- in particular note how the container name is derived.

**Comment by southbanksoftwaredeveloper** [comment]
Makes so much more sense now. The issue was like you said, the `subystem` format in the link you shared. I configured it accordingly and it seems to work as expected. Thanks.
Will close this.
