### ISSUE TITLE
deploy images to daemonsets

### ISSUE THREAD

**Issue by rade** [weaveworks/flux#231]
Currently flux does not deploy images to daemonsets. It should.

**Comment by squaremo** [comment]
The difficulty is that there is no "rolling upgrade" equivalent for daemon sets (either as kubectl command, as for replication controllers, or as a setting as in deployments), which makes it less safe to apply a new configuration.

On the other hand, people clearly do need to upgrade daemon sets with new images, which falls in flux's remit.

**Comment by rade** [comment]
> On the other hand, people clearly do need to upgrade daemon sets with new images, which falls in flux's remit.

Exactly. Right now daemonsets are the only thing in Weave Cloud for which we need to resort to kubectl for deployment, which is unfortunate.

**Comment by squaremo** [comment]
> Right now daemonsets are the only thing in Weave Cloud for which we need to resort to kubectl for deployment, which is unfortunate.

We also use `ConfigMap`s, secrets, and other auxiliary resources, which are not supported in flux but might be.

Daemonsets are a special case, because applying a daemonset config does not trigger any update; i.e., it will succeed without anything actually happening.

How to roll out a daemonset depends a lot on the particular image -- sometimes it is OK to kill all the pods at once, sometimes it's better to do one at a time, sometimes one at a time but waiting for a ready signal from the last, etc...

**Comment by philwinder** [comment]
> 1.6 includes rolling upgrades for DaemonSets.
https://github.com/kubernetes/kubernetes/issues/22543

And after the move to git-sync, we'd just rely on whatever kubectl does.

**Comment by awh** [comment]
Fixed by #747.
