### ISSUE TITLE
Having to indent my ssh key is a bit cumbersome

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/flux#237]
When creating the flux.conf file, making sure the indentation is correct is cumbersome.  Can we not just left justify it or something a bit simpler?

**Comment by squaremo** [comment]
It is a bit. It's down to yaml syntax, rather than something we've invented.

There are a couple of remedies, though. One is that there's alternate syntax in yaml for long strings, using `>` instead of `|`, which doesn't need indenting. `|` looked much neater -- and therefore better for showing in instructions -- but it's true that it's more of a pain to actually supply.

But far better than that, #225 suggests that we can just generate a key pair ourselves, keep the private key, and give the user (or github) the public key -- so the user never has to transmit the private key at all.

**Comment by paulbellamy** [comment]
Will be fixed by: https://github.com/weaveworks/flux/issues/225

**Comment by philwinder** [comment]
Fixed in weaveworks/service#1102
and #431
Users can now auto-generate and insert a deploy key via the UI (requires ui updates).
