### ISSUE TITLE
Error in list-images

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/flux#245]
```
$ fluxctl —token <token>   list-images
Error: executing HTTP request: reading HTTP response: 500 Internal Server Error (getting images for services: fetching image metadata for nats: Get https://index.docker.io/v2/nats/manifests/latest: http: non-successful response (status=401 body="{\"errors\":[{\"code\":\"UNAUTHORIZED\",\"message\":\"authentication required\",``\"detail\":[{\"Type\":\"repository\",\"Name\":\"nats\",\"Action\":\"pull\"}]}]}\n")
```

**Comment by peterbourgon** [comment]
```
Error: executing HTTP request: 
 reading HTTP response: 
  500 Internal Server Error 
   (getting images for services: 
    fetching image metadata for nats: 
     Get https://index.docker.io/v2/nats/manifests/latest: http: 
      non-successful response 
       (status=401 body="
        {"errors":[{
         "code":"UNAUTHORIZED",
         "message":"authentication required",
         "detail":[{
          "Type":"repository",
          "Name":"nats",
          "Action":"pull"
         }]
        }]}
       "))
```

**Comment by squaremo** [comment]
It's a bit surprising it happened for this particular repository, but I would expect there to be some authorisation failures, missing repositories, and so on from time to time. `list-images` would be much more useful if it didn't treat a failure to fetch one repo as fatal, I reckon.

**Comment by peterbourgon** [comment]
Reliably fails on `--service=scope/nats` which is weird.

**Comment by squaremo** [comment]
Fails on `--service=scope/consul` and `--service=scope/memcached`  as well, which have two things in common:

 1. They use a single-word image name `consul:0.7.1`;
 2. They are hosted on Docker Hub rather than quay.io

It _does_ work ok for `--service=scope/control`, which uses `weaveworks/scope`, so I think it's that first one that's suspicious.

The URL `https://index.docker.io/v2/nats/manifests/latest` doesn't look right, I think it should be `https://index.docker.io/v2/r/library/nats/manifests/latest` or similar, is my guess.

**Comment by squaremo** [comment]
> I think it should be https://index.docker.io/v2/r/library/nats/manifests/latest or similar, is my guess.

It should be `https://index.docker.io/v2/library/nats/manifests/latest`.

**Comment by squaremo** [comment]
> list-images would be much more useful if it didn't treat a failure to fetch one repo as fatal, I reckon.

I moved this to #253.
