### ISSUE TITLE
Automated, versioned releases

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#248]
It would be helpful for users if there was a stable, published URL where they could get the latest binary; and it would be helpful for us if those included a version we could ask people for, when troubleshooting for example.

There's a target in the makefile which builds "release binaries" (just fluxctl binaries for `{linux, darwin} x {amd64}`). I propose, then:

 1. Adding a version command which reports the baked-in version of the binary
 2. Baking in a version, at least when building release binaries
 3. Automating releases so that a stable URL is maintained (but not necessarily driving releases from CI)

**Comment by philwinder** [comment]
Requirements:
- As much as possible, follow convention set by weaveworks/weave.
- Should have both linux and osx binaries
- Baked version will be tagged version for GH tags or hash for snapshot versions
- Bake version into: `fluxctl`, `fluxd` and `fluxsvc`

Tasks:
- [ ] Add `fluxctl version` command
- [ ] Add `fluxd version` command
- [ ] Add `fluxsvc version` command
- [ ] Add/reuse `main.version` variable (see [here](https://github.com/weaveworks/flux/blob/master/cmd/fluxctl/version_cmd.go#L9))
- [ ] Add `release-bins` build for `fluxd` and `fluxsvc` (see [here](https://github.com/weaveworks/flux/blob/master/Makefile#L25))
- [ ] Port `release` script from weave repo, rather than encoding release logic in `circle.yml`

Result:
- Each binary will have version baked in
- Users will be able to directly link to the url for a most recent version. E.g.: https://github.com/weaveworks/flux/releases/tag/latest_release
- Users will be able to link to a versioned url E.g.: 
https://github.com/weaveworks/flux/releases/tag/v1.8.2

**Comment by rade** [comment]
I don't think we'd want to release (as in "make available for download") fluxd and fluxsvc binaries. These should only ever be released as container images.
