### ISSUE TITLE
Unusual experience rolling out authfe

### ISSUE THREAD

**Issue by jml** [weaveworks/flux#257]
Apologies in advance that this isn't a well-defined bug. I just wanted to capture an unusual experience rolling out authfe w/ fluxctl in case it helps.

Doing the daily prod roll out, a copy/paste error meant that I accidentally typed `fluxctl release --all --update-image quay.io/weaveworks/authfe:quay.io/weaveworks/authfe` and hit enter.

I hit Ctrl-C as quickly as I could. I got some sort of output, which unfortunately I no longer have access to. 

I then ran the correct command:

```
$ fluxctl release --all --update-image quay.io/weaveworks/authfe:master-8de2e90
```

Which emitted 3 lines of output (again, I don't have it), and hanged.

I went to our `compare-images` page showed production running the revision `quay.io/weaveworks/authfe`.

During this time, I could still access admin pages which were behind the authfe.

Due to time pressure (I can't leave prod broken for long; others were waiting for deploy to clear), I attempted to resolve the problem by running `wcloud deploy quay.io/weaveworks/authfe:master-8de2e90`, which worked.

**Comment by jml** [comment]
Trying again:

```
$ fluxctl release --all --update-image quay.io/weaveworks/authfe:master-53fe5f5
Submitting release job...
Release job submitted, ID c129b41a-b83c-b8ec-4039-821c619e1e66
Status: error querying release.
Error: executing HTTP request: reading HTTP response: 502 Bad Gateway (<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.0 (Ubuntu)</center>
</body>
</html>)
```

**Comment by squaremo** [comment]
I think there's two things going on. The first is that releasing an image without a tag leads to bad things. In general we should stop people deploying an image with no tag, along with #173 perhaps.

The second is that rolling authfe out means disrupting websocket connections from daemons (including the one running in prod). Broadly, the system is tolerant to this, since the daemons will reconnect. But the operations underway will look broken.
