### ISSUE TITLE
Add BI stats

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#271]
So we can find out about the number of installations.

**Comment by philwinder** [comment]
@paulbellamy Can you be a bit more specific?

E.g. 1: Add a bit of code that pushes a ping to some external service, so we can track active usages
E.g. 2: Add some monitoring to the fluxd service in weave cloud so that it sends a counter to prometheus every time someone uses fluxctl with weave cloud
E.g. 3: Some sort of web analytics to monitor the number of views/downloads of the binary

**Comment by paulbellamy** [comment]
@tomwilkie could probably point you at a good example of some other service which does this. My assumption is something like this: https://github.com/weaveworks/service/blob/master/metrics/main.go

**Comment by philwinder** [comment]
So that code posts a list orgs, users and memberships to https://bi.weave.works/import/service/.
Those entities are the same for flux too, so we wouldn't gain anything by adding another service that does the same thing.

But we could add some stuff more specific to flux. However, I'm not sure what that bi url is, or what you can send to it.

**Comment by paulbellamy** [comment]
Ping @tomwilkie for docs on BI.

**Comment by tomwilkie** [comment]
There are no docs I'm afraid.

If you let me know what questions you want to answer, I can help you do that.

**Comment by philwinder** [comment]
"BI has query for number of active flux instances"

@paulbellamy Who requested this? Is this good enough?

**Comment by paulbellamy** [comment]
If the authfe hooks on bi let us do that, then that is good enough.

**Comment by philwinder** [comment]
E.g. query: https://bi.weave.works/#5769015641243648
E.g. dashboarding.
(Both from Tom)
![image](https://cloud.githubusercontent.com/assets/8793723/22144819/f023d080-def6-11e6-84d0-ca728f8c6de3.png)
