### ISSUE TITLE
Garbage collect instance records

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#30]
Problem: instances tend to stick around if you stop an agent or host,
because there's nothing to remove them.

Proposal: run a timer in each agent which refreshes a TTLd key. Peers
should disregard instances that belong to a host that is not present;
so there's an inner join on the {instances, hosts}.

Difficulties:

 * just because the agent isn't running, doesn't mean the instances
   aren't running (although the information is stale, so it is perhaps
   better to be conservative and exclude them; this should be made
   visible)

 * if you restart an agent with a different identity (host IP,
   effectively), how do you make sure you don't get overlapping sets
   of instances

 * whose responsibility is it to remove stale instances, ultimately?

**Comment by dpw** [comment]
> just because the agent isn't running, doesn't mean the instances
> aren't running (although the information is stale, so it is perhaps
> better to be conservative and exclude them; this should be made
> visible)

Is this question prompted that this issue is also about preventing load balancers sending requests to unreachable instances.  But if we accept that that job belongs to the load balancer (which it doesn't do at the moment, but should), and this issue is just about cleaning up stale information, is this still a significant concern?

If we make the TTL fairly long and the refresh time much shorter (say, 5 minutes and 1 minute), then a missing key is a fairly strong indication that an agent has gone away and isn't coming back, and so any information it provided is stale and shouldn't be relied upon.

> if you restart an agent with a different identity (host IP,
> effectively), how do you make sure you don't get overlapping sets
> of instances

Doesn't the use of container IDs as instance IDs ensure this?  You can't have two instances in the same service with the same ID.

> whose responsibility is it to remove stale instances, ultimately?

The combined agent/balancer can also combine a cleaner component with this responsibility.  When it sees an agent go away, it will sweep any lingering instances (it will also need to do a sweep on startup).

A refinement to reduce the amount of redundant etcd operations would be to delay a sweep by a random interval (up to a few minutes).

**Comment by squaremo** [comment]
> If we make the TTL fairly long and the refresh time much shorter (say, 5 minutes and 1 minute), then a missing key is a fairly strong indication that an agent has gone away and isn't coming back, and so any information it provided is stale and shouldn't be relied upon.

Yes it is; though five minutes is a long time to wait to make instances stale (in the absence of other mechanisms). Working in combination with load balancers making their own, local decisions about which instances are healthy might make it acceptable I suppose. It would be hard to make dubious instances visible to the user, perhaps.

> [if] this issue is just about cleaning up stale information, is this still a significant concern?

There are two concerns: don't send traffic to instances you know are defunct, and don't keep records of defunct instances around (for too long). The first is _to some extent_ taken care of by expiring instances when the agent is detected as absent. I was treating changes to the balancer as distinct, but we could fold it in here, since it seems a crucial part of solving the problem.

>> if you restart an agent with a different identity (host IP,
>>     effectively), how do you make sure you don't get overlapping sets
>>     of instances
> 
> Doesn't the use of container IDs as instance IDs ensure this? You can't have two instances in the same service with the same ID.

Yes it does -- it's not a composite key -- disregard ..

> The combined agent/balancer can also combine a cleaner component with this responsibility. When it sees an agent go away, it will sweep any lingering instances (it will also need to do a sweep on startup).
> 
> A refinement to reduce the amount of redundant etcd operations would be to delay a sweep by a random interval (up to a few minutes).

Yeah, that's the conclusion Peter and I came to as well, after a bit of discussion.

**Comment by squaremo** [comment]
> I was treating changes to the balancer as distinct, but we could fold it in here, since it seems a crucial part of solving the problem.

It can be done separately, so long as we do both ...

**Comment by squaremo** [comment]
The store can now be run with a `daemon.StartFunc`, which will start a heartbeat goroutine as well as a scheduled clean-up goroutine. This is only used in `fluxd`, since the other uses of the store don't add records that need to be cleaned up.
