### ISSUE TITLE
Flux should store logs for old releases

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#394]
(and probably the jobs as well)

So that you can look back at what happened in the past.

**Comment by philwinder** [comment]
Isn't this what `fluxctl history` provides?

**Comment by paulbellamy** [comment]
`history` stores the intended releases, but not much info on what happened. The idea was to get more detail on that, but this seems like a good candidate for booting.

**Comment by squaremo** [comment]
By and large, all that happens is one of two things:
 1. it failed because of a specific problem in the preparation (e.g., couldn't clone the repo)
 2. it succeeded, and the changes were committed.

If there's an error we record that in the event. In the latter case, we record what got changed (or why something didn't). For git syncs, we'll similarly record what was deleted and what was applied. So I think we're doing much better at this anyway. (@paulbellamy Reopen if I've misunderstood the intent of the issue.)
