### ISSUE TITLE
Only deploy once when multiple images change

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/flux#404]
Flux seems to require deploying once for every changed image. This is inconvenient for services using multiple images (i.e. if N images have changed, then N deployments are required).

**Comment by philwinder** [comment]
This is by design: https://github.com/weaveworks/flux/blob/master/automator/automator.go#L147

It's actually simpler to perform the deploy in a single release, because we can then reuse the the release code in `releaser.go`.

But goes against the original design. So we need a tip of the hat from @squaremo.

**Comment by squaremo** [comment]
I think this may be referring to how the user interface works: in the CLI you can only deploy one image at a time, and in the web UI you can only deploy one image to one service at a time. So I think this is about supplying more than one `--update-image` argument, e.g.

(In the case of automation, we usually only see one image change anyway, to an approximation.)

**Comment by sambooo** [comment]
If multiple images get updated tags at approximately the same time, they'll now all be combined into the same automated release as of #589.
