### ISSUE TITLE
handling failing deployments

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/flux#457]
When I update a deployment using Flux there is no way for me to know if new pods the deployment created are ready or not. I'd like to trust Flux to ensure only healthy deployments stick around, and I'd hope it could tell me whenever there was an issue and do a rollback for me.

**Comment by paulbellamy** [comment]
Define "failing", please...

**Comment by errordeveloper** [comment]
I suppose "unsuccessful" would be a better word, but in other words the
problem I had was that a deployment resulted in 0 ready pods.

**Comment by paulbellamy** [comment]
I meant, do you have recommended ways we should detect that a deployment has "failed". Some metrics for failure might be difficult to quantify. 0 ready pods after some time would be a good one, though.

**Comment by philwinder** [comment]
I think this is partially the responsibility of kubernetes, not flux.

**Comment by squaremo** [comment]
> I think this is partially the responsibility of kubernetes, not flux.

And monitoring etc.,, where Kubernetes is not adequate. But it would be good, if not in flux, to help close that loop.

Flux does give some status information in it's service listing (a simplified version of what you get from `kubernetes rollout`), but it's not obvious, and informational only.

I'm going to close this issue, but only because we cannot act on it at this time. If we expend the horizon of flux, I'm sure this will come back up.
