### ISSUE TITLE
Allow apply to services that aren't running yet

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#467]
It'd be handy to be able to release a service that exists in configuration but not yet in the running system.

NB this entails sending the service definition to fluxd as well as the deployment, which may end up being a modest hack.

**Comment by SamMorrowDrums** [comment]
Yes, this is a major use-case for people who are running numerous environments. Currently, every time I want to bring the first version of a new service into a new namespace, it involves a manual step for every environment.

For people who use external devops to manage production clusters (for 24x7 support etc.), this means having to contact them to run in new configuration every time a new service is created. That just doesn't feel like a great workflow.

**Comment by squaremo** [comment]
The sync loop will in effect create things that exist in configuration but not in the cluster, because it `kubectl apply`s all resources in the config.

**Comment by SamMorrowDrums** [comment]
If I'm using Flux manually `fluxctl release --service=default/service --update-image=...`, because the current policies for automated deployment don't yet work for my scenario (unless this has changes), will the above command now deploy a new configuration file, when it doesn't yet exist in the cluster?

**Comment by squaremo** [comment]
@SamMorrowDrums If you use the rather new 1.0.0-beta daemon, new configuration will be applied (`kubectl apply`d) to your cluster regularly, including things that need to be created.

    https://github.com/weaveworks/flux/releases/tag/1.0.0-beta

Changing to the newer daemon involves a bit of mechanical faff; and, best try it out in a dev or testing environment for a while to make sure there are no lurking surprises.

> because the current policies for automated deployment don't yet work for my scenario

We've added some means of control over which things get deployed, again in the new release.

https://github.com/weaveworks/flux/pull/589 lets you match image tags against a glob pattern to qualify for automated release. It would be good to know if this would help in your scenario.

**Comment by SamMorrowDrums** [comment]
I've mentioned this issue to one of my colleagues. I'm in the process of moving jobs, and they use Heroku, rather than K8s so I'm not sure when I'm going to get a chance to look at this myself (at least for a while), these changes both sound spot on though, so I'm confident it's going in the right direction!

**Comment by squaremo** [comment]
> so I'm confident it's going in the right direction!

Thank you for that :) Good luck with the move!
