### ISSUE TITLE
Humane errors 

### ISSUE THREAD

**Issue by peterbourgon** [weaveworks/flux#56]
We should use some kind of enhanced error package ([e.g.](https://github.com/pkg/errors)) to produce humane i.e. human-readable errors at the fluxctl command line. I'm thinking something multi-line and literate: this has happened, here are the likely causes, here are some avenues to pursue for debugging/resolution.

- [ ] if the platform is unavailable, we should explain it might not be connected, or if it is (how can you check?), it could be worth trying the operation again (this includes "nats timeout")
- [ ] if the git repo can't be read, that often means the deploy key is missing, or the git URL is wrong
- [ ] fetching image metadata often fails. In this case, trying again may well work; or check the specific repository exists etc.
- [x] `GetRelease` returns a 500 when a job id doesn’t exist: [source](https://github.com/weaveworks/flux/blob/master/http/transport.go#L296)

**Comment by paulbellamy** [comment]
We are already using errors.Wrap, but still have monstrous errors.

**Comment by squaremo** [comment]
Let's start with some of the more egregious errors (either from being obscure, or being common. Or obscure and common.)

 * if the platform is unavailable, we should explain it might not be connected, or if it is (how can you check?), it could be worth trying the operation again (this includes "nats timeout")
 * if the git repo can't be read, that often means the deploy key is missing, or the git URL is wrong
 * fetching image metadata often fails. In this case, trying again may well work; or check the specific repository exists etc.

**Comment by squaremo** [comment]
This basically involves recognising when we have a particular variety of error, and translating that into useful output for the user. However, the question is where should this happen?

Since it's an API, I would go for encoding error responses in JSON, and translating to a message at the server, while the client(s) dispatch on the response code to choose whether to print that message or not.

Deciding on the correct HTTP status codes to use for an API is a bit of a rabbit hole, but we can start simply with

 * 20x -- yes the request succeeded
 * 400 -- the request did not succeed, and won't succeed until the user takes some other action (correcting some config, for example)
 * 404 -- the thing referred to in the URL does not exist (since we don't in general represent entities in URLs, this may be of limited use for now, but if we name instances in the URL it might come into play)
 * 410 -- this API has been removed
 * 500 -- the request did not succeed, for some transient reason in the service; trying again is reasonable.

For payloads, we usually need something to display to the user, and something to log. It's also useful to have something representing the specific kind of error, and the particulars, in case a client wants to use those to e.g., put a link to more help.

```
{
  "error": {
    "kind": "git_access_error",
    "developerMessage": "git repository git@github.com:squaremo/flux-example rejected git clone",
    "userMessage": "Unable to clone the git repository for this instance.\n\nThis may mean you have not supplied a deploy key, or that the deploy key you have supplied does not have access to the repository.",
    "particulars": {
      "fingerprint": "md5 0f:fe:ab:76:...",
      "repository": "git@github.com:squaremo/flux-example",
    },
  }
```

**Comment by squaremo** [comment]
A special case of this is the `check-release` command (and by extension, `release`), since it doesn't get a single error in response, but a trace of a job, which may include an error.
