### ISSUE TITLE
Schedule an automation run when automation is enabled for a service

### ISSUE THREAD

**Issue by awh** [weaveworks/flux#591]
Currently when you enable automation for a service you have to wait up to five minutes to see any images updates applied - scheduling an immediate automation run will result in a better user experience.

**Comment by squaremo** [comment]
#623 made policy update jobs ask for an image poll if something was newly automated.
However, since it separated the git and image polling loops, it was only partially successful. If you ask for an image poll inside the job, chances are that will run straight away (i.e., before the commit has been pulled from upstream), and if so, it will not see the newly automated service as automated!

**Comment by sambooo** [comment]
@squaremo did #661 resolve this?

**Comment by sambooo** [comment]
Flux will now do an automation run after any commit is synced, which happens when automation in enabled.
