### ISSUE TITLE
Apply kubernetes namespaces before all other objects

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#602]
At the minute we load all the manifests and apply them one by one. If you have, say, resources in a namespace that is new, they can fail if the namespace is not created before the files are.

Ultimately, this will succeed on the next sync. But it would have faster turnaround, and look less worrying, if it succeeded the first time around. As an approximation, just running namespaces before resources would be a start.

**Comment by tamarakaufler** [comment]
The implementation is in incorrectly named branch

_756-include-errors-in-sync-events_

**Comment by marccarre** [comment]
Since:

1. Flux (alpha) now supports Helm, and 
2. Helm exposes a [`dependencies.yml`](https://github.com/kubernetes/helm/blob/master/docs/helm/helm_dependency.md) file listing explicitly all dependencies,

does that mean we effectively get this automatically for Helm users?
If not, we might want to try to integrate Flux with this feature of Helm.

**Comment by squaremo** [comment]
> does that mean we effectively get this automatically for Helm users?

It looks like Helm does a crude but effective sort, such that it applies kinds that can be dependencies before other kinds.

We could do that too, since we stage everything before applying.

**Comment by sambooo** [comment]
Note that the original issue as it was originally filed was fixed by #812.

**Comment by sambooo** [comment]
@marccarre "dependencies" in this issue specifically referred to the dependency a namespaced kubernetes object has on the namespace object itself. Applying resources used to fail depending on the order in which it was done because we could attempt to create an object in a namespace which hasn't yet been created.

Helm dependencies are entirely separate from this aspect of Flux. If you think it's something we should be paying attention to, please file a new issue.
