### ISSUE TITLE
"spec: plan" included in history which is a bit noisy and mostly redundant.

### ISSUE THREAD

**Issue by foot** [weaveworks/flux#626]
When making a plan from the UI they're easily dismissed and followed by an `exec` if important.

Unless they're useful for another purpose maybe we could not write them to history.

(unlessss, we start using them as a references for actual releases, e.g. I made this plan `{ "spec": "<all services>" }`, and I've waited an hour and now its changed but I've reviewed and like *this* plan and would like to still run it so `updateImages?plan=c0ffeeb00b00` but I think this is another discussion!)

**Comment by squaremo** [comment]
> maybe we could not write them to history.

Flux used to send commit notifications in the case of a dry run (when there was no actual commit). This was fixed in #616.

Modulo that bug: release events are sent when the sync loop goes "past" a commit that corresponds to a release. A dry-run release doesn't write a commit; and since it doesn't write a commit, there won't be any release event.

**Comment by squaremo** [comment]
i.e., can you make sure you get this problem with current master? :)

**Comment by foot** [comment]
Yes you are right this doesn't happen on dev, will explore locally and re-open
