### ISSUE TITLE
Include user in git commit info

### ISSUE THREAD

**Issue by leth** [weaveworks/flux#695]
A thought that just occured to me (sorry if I missed an issue for it already):
For user-requesed changes, I'd be great if we could set the commit **author** to the user, and the commit **committer** to flux-bot.

**Comment by squaremo** [comment]
An adjacent idea: get the username sent by `fluxctl` from git config (currently it uses the logged-in user).

**Comment by squaremo** [comment]
@leth To check my interpretation:

 * for automated upgrades, use flux-bot as the committer and author
 * for user-initiated changes (releases, lock/unlock, automate/deautomate), use flux-bot as the committer and the user as the author.

Is this right?

**Comment by leth** [comment]
Exactly (assuming my previous research on the semantics of author vs comitter was correct)! :)

**Comment by squaremo** [comment]
Addressed by #735, which introduces a flag for the daemon `--git-set-author`. When supplied (it's false by default, so people don't suddenly have broken systems), the daemon will use the user as the commit author.

It also makes fluxctl populate the user information by looking in git config, rather than using the logged-in user.
