### ISSUE TITLE
Deploy reported as failure incorrectly, probably

### ISSUE THREAD

**Issue by jml** [weaveworks/flux#698]
I just released prometheus 1.7.1 to production via the Weave Cloud deploy UI.

It looks like it was released correctly. We are now running the right version, we don't have alerts, and Prometheus works.

However, the UI said it failed:

<img width="983" alt="screen shot 2017-08-10 at 11 05 37" src="https://user-images.githubusercontent.com/125674/29165831-0b93cbcc-7dbc-11e7-8083-1e446af9f96d.png">

Even though Slack says it didn't:

<img width="907" alt="screen shot 2017-08-10 at 11 07 11" src="https://user-images.githubusercontent.com/125674/29165842-18ff8d3c-7dbc-11e7-82cc-6f07bf00d0bf.png">

**Comment by squaremo** [comment]
Hrm, yes we see this from time to time, regrettably. In essence: flux did all the main things it set out to do, including sending a notification, but fell at a minor last hurdle and reported that back to the user. This is a terrible user experience.

I am reluctant to spend time on it, since flux master does a lot better (though surely has its own sharp corners).

**Comment by jml** [comment]
Ah yeah, sorry, it's a bit hard to keep track of what's deployed where. 

Will close since this is essentially fixed in the next release.
