### ISSUE TITLE
flux returns 500s for various user errors

### ISSUE THREAD

**Issue by jml** [weaveworks/flux#703]
Something of an umbrella issue. It's been reported a few times on Slack that flux returns 500s for certain kinds of user errors. This wreaks havoc with our monitoring, which assumes that 5xx means something wrong with our system.

Unfortunately, I don't have access to specific details right now. I had a quick look at open issues and couldn't find anything relevant, so filing this here. 

Please feel free to close, as long as there's a nice trail of links to actual problems, or a confirmation that this problem is purely imagined.

**Comment by squaremo** [comment]
There are two related causes:

 1. back in the mists of time, the Flux service code assumed any error that got as far as the request handler should provoke a 500. This is not in itself unreasonable, but in general most errors, of any kind, made their way back to the request handler. We eventually fixed this by distinguishing particular user errors, and left 500 as the catch-all only. There are no doubt still some user errors that aren't "converted" in this way.

 2. when most of the operations done on behalf of the user were moved into the daemon, they started being shipped over RPC. Because of the way `net/rpc` works, that meant they were flattened into strings, losing the distinction between user errors and others -- so _all_ of them now get reported as 500s, because they get caught by the catch-all from above.

**Comment by squaremo** [comment]
Addressed by #705

**Comment by squaremo** [comment]
Have also mitigated this in the service by treating any non-connection-dropping errors over RPC as application errors (i.e., 422 rather than 500). See #731.

**Comment by squaremo** [comment]
Of the two causes listed in https://github.com/weaveworks/flux/issues/703#issuecomment-321782251,

 1. still the case -- no doubt some user errors still manifest as system errors -- but an ongoing project that we can improve incrementally. We don't currently see many 500s.
 2. errors are now conveyed over RPC, as mentioned above.
