### ISSUE TITLE
Store whole image data in one place

### ISSUE THREAD

**Issue by squaremo** [weaveworks/flux#710]
At the minute, each scan of our local image manifests involves a large number of memcache requests (one for tags, then one for each tag). It'd be nice to be able to just fetch one thing; when we've managed to assemble a whole set of data, we can regenerate it.

**Comment by philwinder** [comment]
The reason for doing it this way was so that it matches the flow of getting information from a remote repository.

E.g. we have to make an individual HTTP call to get the manifest for each tag.

I think it would complicate the code if we had a different scheme for memcache. So I would only consider this if there was a clear benefit for doing so (i.e. performance).

**Comment by squaremo** [comment]
> So I would only consider this if there was a clear benefit for doing so (i.e. performance).

The idea is that you do one request to memcached instead of hundreds, of which any single request failing will invalidate the whole operation.

**Comment by squaremo** [comment]
(But it is just an idea. I agree that unless it's demonstrably a problem in practice, which I only suspect at this time, we shouldn't hurry to look into this)
