### ISSUE TITLE
Getting a syntax error near unexpected token `newline' when running fluxctl

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/flux#789]
Downloaded `fluxctl` with: 

```
curl -o /usr/local/bin/fluxctl -sSL https://github.com/weaveworks/flux/releases/
```
and then, 

```
chmod +x /usr/local/bin/fluxctl
```
Then I passed it my token like this: 

```
export WEAVE_CLOUD_TOKEN=[token-hidden]
```
ran fluxctl --help and got this: 

```
/usr/local/bin/fluxctl: line 7: syntax error near unexpected token `newline'
/usr/local/bin/fluxctl: line 7: `<!DOCTYPE html>'
```

**Comment by rade** [comment]
I have discussed this with @abuehrle. That curl cannot work since it will just download the github release page html. Moreover, we cannot provide a single command to users because a) flux releases are not published under a mutable tag, so the link changes with every release, and b) there are two versions of the fluxctl binary, one for Mac and one for Linux.

Suggestion is to send users to https://github.com/weaveworks/flux/releases/latest and let them work out themselves which binary to download and how.
