### ISSUE TITLE
Use kubectl apply --record flag

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/flux#85]
Makes rollout history much nicer

**Comment by squaremo** [comment]
(much has changed since this issue was logged, however:) I tried adding `--record` to where we call `kubectl apply`. The effect is that the command used is added as an annotation to the resource, and that annotation is reported when you run `kubectl rollout history <whichever deployment it was>`.

Because of the way we call `kubectl apply`, what's recorded ends up being pretty uninteresting -- all the arguments are about authentication, and the actual resource is supplied over stdin and doesn't appear even as a filename -- and all look the same.

If we use `kubectl apply` or other subcommands in more varying ways in the future, this will again be worth considering.
