### ISSUE TITLE
Empty config repo with no commits gives git.status = new and leaves user confused.

### ISSUE THREAD

**Issue by foot** [weaveworks/flux#904]
This is pretty edge casey but confusing if you're following a tutorial and don't completely understand what you're doing yet and so create a blank repo and end up in a bit of un-helpful-error-message state.

```sh
$ git clone git@github.com:foot/emptier-repo.git
Cloning into 'emptier-repo'...
warning: You appear to have cloned an empty repository.
$ echo $?
0
$ git tag zing
fatal: Failed to resolve 'HEAD' as a valid ref.
$ echo $?
128
```

- Anywho, I guess ideally we should create a commit we can tag.
- Or ... an error to the user saying empty repo's are no good.

**Comment by squaremo** [comment]
Oooh well spotted. Yes, we ought to do something more sensible in this case. /me puts on thinking hat ...

**Comment by squaremo** [comment]
Note to fixer: please check that any fix also alleviates the symptoms explained in #1173.

**Comment by dlespiau** [comment]
My first thought was to push a branch with a commit. But that's still problematic because github will refuse to delete the first branch that appears in a git repo (it becomes the default branch!)
```
$ git clone git@github.com:dlespiau/emptyrepo.git
$ git checkout -b flux-write-test-4bfed10f1214c58d972b1be6bc009349
$ git commit -allow-empty -m "flux-write-test"
$ git push origin flux-write-test-4bfed10f1214c58d972b1be6bc009349:flux-write-test-4bfed10f1214c58d972b1be6bc009349
$ git push origin :flux-write-test-4bfed10f1214c58d972b1be6bc009349
To git@github.com:dlespiau/emptyrepo.git
 ! [remote rejected] flux-write-test-4bfed10f1214c58d972b1be6bc009349 (refusing to delete the current branch: refs/heads/flux-write-test-4bfed10f1214c58d972b1be6bc009349
```

We can be more cunning though! we can still push (and delete) a tag:

```
$ git clone git@github.com:dlespiau/emptyrepo.git
$ git checkout -b flux-write-test-4bfed10f1214c58d972b1be6bc009349
$ git commit --allow-empty -m "flux-write-test"
$ git tag write-test
$ git push --tags
Counting objects: 2, done.
Writing objects: 100% (2/2), 170 bytes | 0 bytes/s, done.
Total 2 (delta 0), reused 0 (delta 0)
To git@github.com:dlespiau/emptyrepo.git
 * [new tag]         write-test -> write-test
$ git push origin :write-test
To git@github.com:dlespiau/emptyrepo.git
 - [deleted]         write-test
```

**Comment by squaremo** [comment]
That _is_ pretty cunning, I think that recipe would work. Well thought through Damien

**Comment by hiddeco** [comment]
Was looking for a lightweight task as I was on support rota today and laid my eyes on this; it turned out to be more of a pain than I was prepared for.

To be clear, there is nothing wrong with your recipe @dlespiau, but I am afraid Flux does not perform the write check on a regular `git clone`, but on a mirror / bare clone (`git clone --mirror`) where branching is not possible.

```
$ git clone --mirror git@github.com:hiddeco/emptyrepo.git
$ git checkout -b flux-write-test-4bfed10f1214c58d972b1be6bc009349
fatal: this operation must be run in a work tree
```

I tried to configuring the default branch in the bare clone and push that but without any luck (configuring is not an issue but apparently you can't update the remote to this setting).

```
$ git symbolic-ref HEAD refs/heads/configured-flux-branch
$ git push
No refs in common and none specified; doing nothing.
Perhaps you should specify a branch such as 'master'.
error: failed to push some refs to 'git@github.com:hiddeco/emptyrepo.git'
$ git push --all
No refs in common and none specified; doing nothing.
Perhaps you should specify a branch such as 'master'.
error: failed to push some refs to 'git@github.com:hiddeco/emptyrepo.git'
```

**Comment by dlespiau** [comment]
Argh! and I'm guessing that's the same story for the second solution based on tags?

**Comment by hiddeco** [comment]
I tried the second solution, the problem is that we need to create a branch for this (which we do not actually push), so that we can create an empty commit which gives us a reference we can point the tag to (which we do push).

With a bare clone this is never going to work, the only actions you can perform in a bare clone are things like creating new tags pointing towards existing references (of which we have none).

We could use a normal clone, but we would never be able to revert back to an empty state, as, as you already noticed, git will reject removing the default branch.

My conclusion is that instead of performing the write check, we should inform the user we can not move forward with operations without an existing branch, probably by detecting the branch we are told to look for does not exist / has no `HEAD`.
