### ISSUE TITLE
Flux master isn't moving the sync tag

### ISSUE THREAD

**Issue by sambooo** [weaveworks/flux#967]
Some change in #940 broke moving the tag in the upstream repo. Track findings here, or hopefully just close with a simple fix.

**Comment by squaremo** [comment]
I tried a fluxd built from master, giving it an upstream of an instance on our dev env. It sent notifications fine, when I did a push-button release, and after I turned automation on :/

Worth verifying this for yourself of course. Otherwise, perhaps we could try putting the more recent fluxd back in dev and watching the logs for errors while doing push-button releases etc.

**Comment by sambooo** [comment]
I'll unlock dev, let it release the latest flux, and report back. 🤓

**Comment by sambooo** [comment]
Still broken for now it seems

**Comment by squaremo** [comment]
> Still broken for now it seems

But did you get the logs? That was the point of the exercise!

**Comment by squaremo** [comment]
OK I have some logs now. The important message is this (and its ilk):

```
ts=2018-02-28T10:25:21.26352628Z caller=logging.go:66 component=upstream method=SyncStatus error="fatal: ambiguous argument 'k8s/dev': unknown revision or path not in the working tree."
```

i.e., I've got the `git` arguments wrong somewhere. Checking it out now, locally.

**Comment by sambooo** [comment]
I grepped the logs for errors and didn't find that one. Failure on my part I suppose. Good find 👍
